### ISSUE TITLE
Test and improve intel support

### ISSUE THREAD

**Issue by eppane** [nod-ai/serve#13]
Currently TorchServe has support for Intel GPUs:

[examples/intel_extension_for_pytorch](https://github.com/nod-ai/serve/tree/master/examples/intel_extension_for_pytorch)

- Support is provided more as an extension rather than being inherent part of TorchServe

- Nevertheless, TorchServe with Intel® Extension for PyTorch* can deploy any model and do inference.
- To use TorchServe with Intel GPU, the machine must have the latest oneAPI Base Kit installed, activated, and ipex GPU installed.
- There is a custom [intel_gpu_metric_collector.py](https://github.com/nod-ai/serve/blob/master/examples/intel_extension_for_pytorch/intel_gpu_metric_collector.py) provided that needs to be used, rather than the existing [metric_collector.py](https://github.com/nod-ai/serve/blob/master/ts/metrics/metric_collector.py) in TorchServe

Action points:

- Integrate Intel support as an inherent part of TorchServe
- Integrate the provided custom metric collector script to TorchServe
    - See also [print_env_info.py](https://github.com/nod-ai/serve/blob/master/ts_scripts/print_env_info.py)

**Comment by eppane** [comment]
Some notes:
[torch.xpu — PyTorch 2.5 documentation](https://pytorch.org/docs/stable/xpu.html) 
[torch.xpu.is_available — PyTorch 2.5 documentation](https://pytorch.org/docs/stable/generated/torch.xpu.is_available.html#torch.xpu.is_available) 
[Intel® Extension for PyTorch* — PyTorch Tutorials 2.5.0+cu124 documentation](https://pytorch.org/tutorials/recipes/intel_extension_for_pytorch.html) 
[GitHub - intel/intel-extension-for-pytorch at xpu-main](https://github.com/intel/intel-extension-for-pytorch/tree/xpu-main) 
[Examples — Intel&#174 Extension for PyTorch* 2.3.110+xpu documentation](https://intel.github.io/intel-extension-for-pytorch/xpu/latest/tutorials/examples.html) 
[pytorch/torch/xpu/memory.py at main · pytorch/pytorch](https://github.com/pytorch/pytorch/blob/main/torch/xpu/memory.py) 
[Tensor Attributes — PyTorch 2.5 documentation](https://pytorch.org/docs/stable/tensor_attributes.html#torch-device)

**Comment by jakki-amd** [comment]
Won't fix this as not relevant
